version: '3.8'

services:
  cenarium:
    image: cenarium-front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:80
    expose:
      - 3001